### PR TITLE
Logging, refactor context

### PR DESCRIPTION
**Pull request by breton16**

### CODE REVIEW

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @breton16 awake?

**Comment by breton16** [comment]
Yo

**Comment by breton16** [comment]
wat

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @abirismyname awake?

**Comment by abirismyname** [comment]
is @manishapriya94 awake?

**Comment by abirismyname** [comment]
is @manishapriya94 awake?

**Comment by abirismyname** [comment]
is rufusmbugua awake?

**Comment by abirismyname** [comment]
is rufusmbugua awake?

**Pull request merged**
